<?php

namespace App\Traits;

trait FillableTraits
{
    protected array $users = [

    ];

    protected array $bookings = [
        'region_id',
        'driver_id',
        'customer_id',
        'fee',
        'reference',
        'pick_up_date',
        'pick_up_time',
        'drop_off_date',
        'drop_off_time',
        'pick_location',
        'drop_off_location',
        'status',
        'payment_status',
        'payment_method',
        'pick_up_lat',
        'pick_up_lng',
        'drop_off_lat',
        'drop_off_lng',

        'car_id',
        'completed',
        'cancelled',
        'rating',
        'rating_comment',


        'extra_time_price',

        'discount',
        'tax',
        'grand_total',

        'rental_id',

        'booking_type',
        'driver_earn',
        'commission',
        'cancellation_reason',
        'cancelled_by',
        'comment',
        'picked',

        'booking_number',
        'confirmation_no',
        'is_confirmed',
        'insurance_fee',
        'deposit_fee',
    ];

    protected array $car_extra = [
        'is_taxed',
        'car_id',
        'mots',
        'tax_expiry_date',
        'tax_amount',
        'tax_type',
        'service',
        'documents',
        'subscriptions',
        'finance',
        'damage_history',
        'repairs',
        ];

    protected array $car = [
        'driver_id',
        'title',
        'make',
        'model',
        'type',
        'year',
        'color',
        'gear',
        'door',
        'vehicle_no',
        'region_id',
        'is_available',

        'rental_packages',
        'image',
        'company_id',

        'country',
        'state',
        'city',
        'price_per_day',
        'attributes',
        'photos',
        'youtube_link',

        'deposit',
        'bags',
        'cancellation_fee',
        'price_per_mileage',
        'mileage',
        'map_lat',
        'map_lng',
        'requirements',
        'security_deposit',
        'damage_excess',
        'insurance_fee',
        'mileage_text',
        'air_condition',
        'seats',
        'pick_up_location',
        'extras',
        'drop_off_instruction',
        'pickup_instruction',

        'engine_size',
        'fuel_type',
        'body_type',

        'license_no',
        'tracker_no',
        'description',
        'registration_number',
    ];

    protected array $user = [
        'first_name',
        'last_name',
        'avatar',
        'email',
        'phone',
        'is_online',
        'map_lat',
        'map_lng',
        'email_verified_at',
        'password',
        'comment',
        'status',
        'address',
        'country_code',
        'country',
        'city',
        'region_id',
        'service_id',
        'company_id',
        'push_token',
        'last_notification',
        'monify_account',


    ];

    protected $trip_request = [
        'region_id',
        'driver_id',
        'customer_id',
        'fee',
        'reference',
        'origin',
        'destination',
        'status',
        'payment_status',
        'payment_method',
        'origin_lat',
        'origin_lng',
        'destination_lat',
        'destination_lng',
        'started_at',
        'end_at',
        'current_lat',
        'current_lng',
        'distance',
        'distance_text',
        'duration',
        'duration_text',
        'car_id',
        'completed',
        'cancelled',
        'rating',
        'driver_rating',
        'rating_comment',
        'driver_rating_comment',
        'driver_feedback',
        'rider_feedback',
        'base_price',
        'time_price',
        'distance_price',
        'discount',
        'tax',
        'grand_total',
        'service_id',
        'ride_type',
        'scheduled',
        'driver_earn',
        'commission',
        'cancellation_reason',
        'cancelled_by',
    ];
}
